model_config:
  pv3d:
    base_ckpt_path: ""
    pretrained_ckpt_path: ""

    generator:
      z_dim: 512
      c_dim: 25
      w_dim: 512
      img_resolution: 512
      img_channels: 3
      mapping_kwargs:
        num_layers: 2
      channel_base: 32768
      channel_max: 512
      fused_modconv_default: inference_only
      num_fp16_res: 0
      conv_clamp: null
      rendering_kwargs:
        image_resolution: 512
        disparity_space_sampling: false
        clamp_mode: softplus
        superresolution_module: lib.models.videg3d.networks.superresolution.SuperresolutionHybrid8XDC
        superresolution_noise_mode: none
        c_gen_conditioning_zero: false
        gpc_reg_prob: 0.5
        c_scale: 1.0
        density_reg: 0.25
        reg_type: l1
        density_reg_p_dist: 0.004
        decoder_lr_mul: 1.0
        sr_antialias: true
        depth_resolution: 48
        depth_resolution_importance: 48
        ray_start: 2.25
        ray_end: 3.3
        box_warp: 1
        avg_camera_radius: 2.7
        avg_camera_pivot:
          - 0.
          - 0.
          - 0.2
      sr_num_fp16_res: 4
      sr_kwargs:
        channel_base: 32768
        channel_max: 512
        fused_modconv_default: inference_only
    
    density_reg: 1.0

    img_discriminator:
      c_dim: ${model_config.pv3d.generator.c_dim}
      img_resolution: 512
      img_channels: 3
      channel_base: 32768
      channel_max: 512
      num_fp16_res: 4
      conv_clamp: 256
      disc_c_noise: 0.0
      block_kwargs:
        freeze_layers: 0
      mapping_kwargs: {}
      epilogue_kwargs:
        mbstd_group_size: 4

    vid_discriminator:
      c_dim: ${model_config.pv3d.generator.c_dim}
      img_resolution: 512
      img_channels: 3
      channel_base: 32768
      channel_max: 512
      num_fp16_res: 4
      conv_clamp: 256
      disc_c_noise: 0.0
      block_kwargs:
        freeze_layers: 0
      mapping_kwargs: {}
      epilogue_kwargs:
        mbstd_group_size: 4
    
    use_ema: ${training.use_ema}
    neural_rendering_resolution_final: ${training.rendering_resolution}

    losses:
      - type: adv_video
        params:
          eval_applicable: false
          loss_disc_reg_weight: ${training.disc_reg_interval}
          loss_gen_reg_weight: ${training.gen_reg_interval}
          loss_density_reg_weight: ${model_config.pv3d.density_reg}
          loss_img_weight: 1.0
          loss_vid_weight: 1.0
          r1_gamma: 1.0